language: ruby
rvm:
  - 2.5.5
cache: bundler
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir bin
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH
script:
  - bundle exec rspec
